on:
    push:
      branches: ["main"]
jobs:
  CI-main:
    name: CI-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        #with:
            #cache-dependency-path: ./tailwind/package-lock.json
      - name: install dependencies
        run: npm ci
        working-directory: ./tailwind
      - name: Run tests
        run: npm run test:ci
        working-directory: ./tailwind
      - name: Build
        run: npm run build
        