on:
    push:
      branches: ["main"]
jobs:
  CI-main:
    name: CI-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
        working-directory: ./tailwind
      - name: Run tests
        run: npm run test:ci
        working-directory: ./tailwind
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./tailwind
          file: ./tailwind/Dockerfile
          push: true
          tags: |
            oswe/tech-trend-emporium-TEST-prod:${{ github.sha }}
            oswe/tech-trend-emporium-TEST-prod:latest
        