on:
    push:
      branches: ["main"]
jobs:
  CI-main:
    name: CI-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
        working-directory: ./tailwind
      - name: Run tests
        id: testMain
        run: npm run test:ci
        working-directory: ./tailwind
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./tailwind
          file: ./tailwind/Dockerfile
          push: true
          tags: |
            oswe/tech-trend-emporium-test-prod:${{ github.sha }}
            oswe/tech-trend-emporium-test-prod:latest
          build-args: |
            CONFIGURATION=local
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: ${{ github.job }} job of ${{ github.repository }} - ${{ job.status }}
            body: |
                The job ${{ github.job }} in workflow ${{ github.workflow }} of repository ${{ github.repository }} - ${{ job.status }}.
    
                Commit: ${{ github.sha }}
                Commit Author: ${{ github.actor }}
                Commit Message: ${{ github.event.head_commit.message }}
    
                Test Status:
                ${{ steps.testMain.outcome != 'success' && 'Some tests failed.' || 'All tests passed successfully.' }}
    
                For more details, visit the https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            to: ${{secrets.EMAIL_WORKERS}}
            from: Tech-trend-emporium-fronted